##############################################################################
# Copyright (c) 2016-22, Lawrence Livermore National Security, LLC and Umpire
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - build_and_test

rocm_5.1.0_fortran_clang_13_0_0 (build and test on corona):
  variables:
    SPEC: "+fortran+rocm~tools amdgpu_target=gfx906 %clang@13.0.0 ^blt@develop ^hip@5.1.0"
  extends: .build_and_test_on_corona

###
# This job intentionally tests our umpire package.py because although this job does not
# explicitly have the ~tools, the package.py should still disable tools from being built.
###
rocm_5.1.0_openmp_fortran_clang_13_0_0(build and test on corona):
  variables:
    SPEC: "+fortran+rocm+openmp amdgpu_target=gfx906 %clang@13.0.0 ^blt@develop ^hip@5.1.0"
  extends: .build_and_test_on_corona

include:
  - local: .gitlab/configs/common.yml
  - local: .gitlab/configs/corona-config.yml
