##############################################################################
# Copyright (c) 2016-22, Lawrence Livermore National Security, LLC and Umpire
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - build_and_test

# CPU ONLY
ibm_clang_9:
  variables:
    SPEC: "+fortran %clang@ibm.9.0.0"
  extends: .build_and_test_on_lassen

ibm_clang_9_gcc_8:
  variables:
    SPEC: "+fortran %clang@ibm.9.0.0 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1"
  extends: .build_and_test_on_lassen

clang_10_0_1_mpi (build and test on lassen):
  variables:
    SPEC: "%clang@ibm.10.0.1 +mpi ^spectrum-mpi"
  extends: .build_and_test_on_lassen

clang_10_0_1_mpi_shmem:
  variables:
    SPEC: "%clang@ibm.10.0.1 +ipc_shmem +mpi ^spectrum-mpi"
  extends: .build_and_test_on_lassen

gcc_8_3_1:
  variables:
    SPEC: "+fortran%gcc@8.3.1"
  extends: .build_and_test_on_lassen

pgi_19_10:
  variables:
    SPEC: "+fortran%pgi@19.10 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1"
  extends: .build_and_test_on_lassen

pgi_19_10_gcc_8_3_1:
  variables:
    SPEC: "+fortran%pgi@19.10 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1"
  extends: .build_and_test_on_lassen

pgi_20_4_gcc_8_3_1:
  variables:
    SPEC: "+fortran%pgi@20.4 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1"
  extends: .build_and_test_on_lassen

xl_16_1_1_10:
  variables:
    SPEC: "+fortran%xl@16.1.1.10"
  extends: .build_and_test_on_lassen

xl_16_1_1_10_gcc_8_3_1:
  variables:
    SPEC: "+fortran%xl@16.1.1.10 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1"
  extends: .build_and_test_on_lassen

# CUDA

ibm_clang_9_cuda:
  variables:
    SPEC: "+fortran+cuda %clang@ibm.9.0.0 ^cuda@10.1.168"
  extends: .build_and_test_on_lassen

ibm_clang_9_gcc_8_cuda:
  variables:
    SPEC: "+fortran+cuda %clang@ibm.9.0.0 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 ^cuda@10.1.168"
  extends: .build_and_test_on_lassen

clang_10_0_1_cuda_mpi_shmem:
  variables:
    SPEC: "%clang@ibm.10.0.1 +cuda +ipc_shmem +mpi ^spectrum-mpi ^cuda@10.1.168"
  extends: .build_and_test_on_lassen

gcc_8_3_1_cuda:
  variables:
    SPEC: "+fortran+cuda %gcc@8.3.1 ^cuda@10.1.168"
  extends: .build_and_test_on_lassen

xl_16_1_1_10_cuda:
  variables:
    SPEC: "+fortran+cuda %xl@16.1.1.10 ^cuda@10.1.168 ^cmake@3.14.5"
  extends: .build_and_test_on_lassen

xl_16_1_1_10_gcc_8_3_1_cuda_11:
  variables:
    SPEC: "+fortran+cuda tests=none %xl@16.1.1.10 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 ^cuda@11.0.2"
  extends: .build_and_test_on_lassen

# EXTRAS

clang_9_0_0_libcpp (build and test on lassen):
  variables:
    SPEC: "%clang@9.0.0+libcpp cxxflags='-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0' cflags='-DGTEST_HAS_CXXABI_H_=0'"
  extends: .build_and_test_on_lassen

clang_9_0_0_memleak (build and test on lassen):
  variables:
    SPEC: "+asan +sanitizer_tests %clang@9.0.0 cxxflags=-fsanitize=address"
    ASAN_OPTIONS: "detect_leaks=1"
  extends: .build_and_test_on_lassen

# clang_9_0_0_datarace (build and test on lassen):
#   variables:
#     SPEC: "%clang@9.0.0 cxxflags=-fsanitize=thread"
#   allow_failure: true
#   extends: .build_and_test_on_lassen

gcc_8_3_1_dev_benchmarks:
  variables:
    SPEC: "+dev_benchmarks %gcc@8.3.1 build_type=Release"
  extends: .build_and_test_on_lassen

xl_default_omp_target (build and test on lassen):
  variables:
    SPEC: "%xl@default+openmp+openmp_target ^cmake@3.14.5"
  extends: .build_and_test_on_lassen

gcc_8_3_1_numa:
  variables:
    SPEC: "+fortran+numa%gcc@8.3.1"
  extends: .build_and_test_on_lassen

# Develop/main builds against specific tpl versions

gcc_8_3_1_tpls:
  variables:
    SPEC: "+fortran%gcc@8.3.1 ^blt@develop"
  extends: .build_and_test_on_lassen

ibm_clang_9_gcc_8_cuda_tpls:
  variables:
    SPEC: "+fortran+cuda %clang@ibm.9.0.0 cxxflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 cflags=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 ^blt@develop ^cuda@10.1.168"
  extends: .build_and_test_on_lassen

xl_16_1_1_10_cuda_tpls:
  variables:
    SPEC: "+fortran+cuda %xl@16.1.1.10 ^blt@develop ^cuda@10.1.168 ^cmake@3.14.5"
  extends: .build_and_test_on_lassen

include:
  - local: .gitlab/configs/common.yml
  - local: .gitlab/configs/lassen-config.yml
