##############################################################################
# Copyright (c) 2016-22, Lawrence Livermore National Security, LLC and Umpire
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

# Shared configuration of jobs for corona.

# These are templates (.name) that can be included in other jobs to share part
# of the job definition.
.on_corona:
  tags:
    - shell
    - corona
  rules:
    # Runs except if we explicitly deactivate corona by variable.
    - if: '$ON_CORONA == "OFF"'
      when: never
    # Advanced jobs can only run on master, develop or if ALL_TARGETS is ON.
    # Set ADVANCED_JOB to ON in the job definition to make it an advanced job.
    - if: '$ADVANCED_JOB == "ON" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $ALL_TARGETS != "ON"'
      when: never
    # We should always release resources allocated before.
    - if: '$CI_JOB_NAME =~ /release_resources/'
      when: always
    # A true statement is expected to allow jobs to run. Here is the default.
    - when: on_success

.build_toss_4_x86_64_ib_corona_script:
  script:
    - srun -p pbatch -t 30 -N 1 scripts/gitlab/build_and_test.sh
  artifacts:
    reports:
      junit: junit.xml

.build_and_test_on_corona:
  extends: [.build_toss_4_x86_64_ib_corona_script, .on_corona]
  stage: build_and_test
